builds:
  - goos:
      - linux
    ldflags:
      - -X github.com/google/cadvisor/version.Version={{.Tag}}
      - -X github.com/google/cadvisor/version.Revision={{.Commit}}
      - -X github.com/google/cadvisor/version.Branch={{.Branch}}
      - -X github.com/google/cadvisor/version.BuildUser={{.Env.GITHUB_ACTOR}}
      - -X github.com/google/cadvisor/version.BuildDate={{.Date}}
      - -X github.com/google/cadvisor/version.GoVersion={{.Env.GOLANG_VERSION}}
archives:
  - format: binary
checksum:
  name_template: checksums.txt
